### PR TITLE
Rename installer files in Gradle

### PR DESCRIPTION
**Pull request by ssoloff**
Submitting just in case you want to add it as part of triplea-game/triplea#2032.  It only touches file hunks you've already changed.

### CODE REVIEW

**Comment by RoiEXLab** [comment]
@ssoloff I think this is out-of-scope for https://github.com/triplea-game/triplea/pull/2032, but I'd like to encourage you to completely replace the `build_installers` file with additional buildscipt code. (e.g. we'd only need to call `./gradlew release` instead of `./build_installers`).
Shouldn't be that difficult as game_engine.properties is a properties file which is supported by the JVM ([Found something](https://stackoverflow.com/a/20549712))

**Comment by ssoloff** [comment]
NP, @RoiEXLab.  I will submit a follow-up PR after triplea-game#2032 is merged.

The problem with moving the update of `game_engine.properties` to the Gradle build with this change is that it will lead to the Gradle build becoming non-idempotent, which is not a good thing in a dev environment (could lead to accidental commits of a modified `game_engine.properties`).  It may require a bigger change to adjust how we update this file (e.g. moving it to `src/main/resources` and having the modified copy go to `build/resources/main` or something).

**Comment by RoiEXLab** [comment]
@ssoloff adding another gradle task could fix this issue

**Comment by RoiEXLab** [comment]
@ssoloff I have a better Idea.
Instead of adding a new task you could just change tha value back,
e.g. read the current value and store it in a variable, change the build number and paste it in and after the release task is over you can just set the value back to the initial value.

**Pull request closed without merging**
